class TestData {
  static String integratedCrfJson = '''
{
  "DD": [
    {
      "study_oid": "C240001",
      "form_seq": 4078,
      "item_seq": 23687,
      "item_uid": "5bebf176cbc34b6c9c46408454d278ed",
      "item_oid": "ID_0137",
      "item_name": "ITEM_140_2",
      "data_type": "String",
      "item_label": "CRCRA 등록번호",
      "item_length": "9",
      "input_type": "TextBox",
      "input_type_label": "TextBox",
      "ins_dt": "2025-03-12 15:19:35",
      "ins_id": "TEST0331",
      "ins_ip": "172.18.0.10",
      "upd_dt": "2025-03-12 15:19:35",
      "upd_id": "TEST0331",
      "upd_ip": "172.18.0.10",
      "length": "9",
      "mandatory": "N",
      "order_number": 1,
      "list_yn": "N",
      "is_match": "Y",
      "itemgroup_seq": 7064,
      "repeating": "N"
    },
    {
      "study_oid": "C240001",
      "form_seq": 4078,
      "item_seq": 23688,
      "item_uid": "5e4cc23080d9465c825186a1d18c6717",
      "item_oid": "ID_0138",
      "item_name": "DMDTC_2",
      "data_type": "Date",
      "item_label": "CRCRA 등록일",
      "input_type": "Date",
      "input_type_label": "Date",
      "ins_dt": "2025-03-12 15:19:35",
      "ins_id": "TEST0331",
      "ins_ip": "172.18.0.10",
      "upd_dt": "2025-03-12 15:19:35",
      "upd_id": "TEST0331",
      "upd_ip": "172.18.0.10",
      "mandatory": "N",
      "order_number": 2,
      "list_yn": "N",
      "is_match": "Y",
      "itemgroup_seq": 7064,
      "repeating": "N"
    },
    {
      "study_oid": "C240001",
      "form_seq": 4078,
      "item_seq": 23689,
      "item_uid": "4dfdd36777604e4e8f10d14d453add45",
      "item_oid": "ID_0139",
      "item_name": "Calculate_1",
      "data_type": "Integer",
      "item_label": "Calculate",
      "item_length": "5",
      "input_type": "Calculate",
      "input_type_label": "Calculate",
      "ins_dt": "2025-03-12 15:19:35",
      "ins_id": "TEST0331",
      "ins_ip": "172.18.0.10",
      "upd_dt": "2025-03-12 15:19:35",
      "upd_id": "TEST0331",
      "upd_ip": "172.18.0.10",
      "length": "5",
      "mandatory": "N",
      "measurement_unit": "pg/㎖",
      "order_number": 3,
      "list_yn": "N",
      "is_match": "Y",
      "itemgroup_seq": 7068,
      "repeating": "N"
    },
    {
      "study_oid": "C240001",
      "form_seq": 4078,
      "item_seq": 23690,
      "item_uid": "2ce1096de4114254ba2fb6b1ee1671b1",
      "item_oid": "ID_0140",
      "item_name": "COVAL_1",
      "data_type": "String",
      "item_label": "biomarker 혈액 검체 미채취 기타 이유",
      "input_type": "Comments",
      "input_type_label": "Multi TextBox",
      "ins_dt": "2025-03-12 15:19:35",
      "ins_id": "TEST0331",
      "ins_ip": "172.18.0.10",
      "upd_dt": "2025-03-12 15:19:35",
      "upd_id": "TEST0331",
      "upd_ip": "172.18.0.10",
      "mandatory": "N",
      "order_number": 4,
      "list_yn": "N",
      "is_match": "Y",
      "itemgroup_seq": 7068,
      "repeating": "N"
    },
    {
      "study_oid": "C240001",
      "form_seq": 4078,
      "item_seq": 23691,
      "item_uid": "c60d7d72b69a497d93bca1476b836877",
      "item_oid": "ID_0141",
      "item_name": "AGE_5",
      "data_type": "Integer",
      "item_label": "AGE",
      "item_length": "3",
      "input_type": "TextBox",
      "input_type_label": "TextBox",
      "ins_dt": "2025-03-12 15:19:46",
      "ins_id": "TEST0331",
      "ins_ip": "172.18.0.10",
      "upd_dt": "2025-03-12 15:19:46",
      "upd_id": "TEST0331",
      "upd_ip": "172.18.0.10",
      "length": "3",
      "mandatory": "N",
      "measurement_unit": "세",
      "order_number": 5,
      "list_yn": "N",
      "is_match": "Y",
      "itemgroup_seq": 7068,
      "repeating": "N"
    },
    {
      "study_oid": "C240001",
      "form_seq": 4078,
      "item_seq": 23692,
      "item_uid": "8606ceda52ce45e7a339f406884418eb",
      "item_oid": "ID_0142",
      "item_name": "VISIT",
      "data_type": "Integer",
      "item_label": "예정된 방문 여부",
      "input_type": "Radio",
      "input_type_label": "Radio Button",
      "code_list": "1=Planned|2=Unscheduled",
      "ins_dt": "2025-03-12 15:20:07",
      "ins_id": "TEST0331",
      "ins_ip": "172.18.0.10",
      "upd_dt": "2025-03-12 15:20:07",
      "upd_id": "TEST0331",
      "upd_ip": "172.18.0.10",
      "mandatory": "N",
      "order_number": 6,
      "list_yn": "N",
      "is_match": "Y",
      "itemgroup_seq": 7069,
      "repeating": "N"
    },
    {
      "study_oid": "C240001",
      "form_seq": 4078,
      "item_seq": 23693,
      "item_uid": "101a46966a3444389b025cdcc708e136",
      "item_oid": "ID_0143",
      "item_name": "EXDOSU_1",
      "data_type": "Integer",
      "item_label": "약물 투여 단위 종류",
      "input_type": "DropDown",
      "input_type_label": "DropDown",
      "code_list": "1=mg|2=복합제(tab/cap)",
      "ins_dt": "2025-03-12 15:20:21",
      "ins_id": "TEST0331",
      "ins_ip": "172.18.0.10",
      "upd_dt": "2025-03-12 15:20:21",
      "upd_id": "TEST0331",
      "upd_ip": "172.18.0.10",
      "mandatory": "N",
      "order_number": 7,
      "list_yn": "N",
      "is_match": "Y",
      "itemgroup_seq": 7069,
      "repeating": "N"
    },
    {
      "study_oid": "C240001",
      "form_seq": 4078,
      "item_seq": 23694,
      "item_uid": "57089ae0e4e1469695f7ed9694cbadf9",
      "item_oid": "ID_0144",
      "item_name": "SUDOSTOT",
      "data_type": "String",
      "item_label": "흡연량",
      "input_type": "TextBox",
      "input_type_label": "TextBox",
      "ins_dt": "2025-03-12 15:20:41",
      "ins_id": "TEST0331",
      "ins_ip": "172.18.0.10",
      "upd_dt": "2025-03-12 15:20:41",
      "upd_id": "TEST0331",
      "upd_ip": "172.18.0.10",
      "mandatory": "N",
      "measurement_unit": "cigarette(s)",
      "order_number": 8,
      "list_yn": "N",
      "is_match": "Y",
      "itemgroup_seq": 7069,
      "repeating": "N"
    },
    {
      "study_oid": "C240001",
      "form_seq": 4078,
      "item_seq": 23695,
      "item_uid": "ce3c661a01574127a41f6f44c9c72d6b",
      "item_oid": "ID_0145",
      "item_name": "MHSTDTC",
      "data_type": "String",
      "item_label": "Date of Surgery",
      "item_length": "6",
      "input_type": "TextBox",
      "input_type_label": "TextBox",
      "ins_dt": "2025-03-12 15:20:51",
      "ins_id": "TEST0331",
      "ins_ip": "172.18.0.10",
      "upd_dt": "2025-03-12 15:20:51",
      "upd_id": "TEST0331",
      "upd_ip": "172.18.0.10",
      "length": "6",
      "mandatory": "N",
      "order_number": 9,
      "list_yn": "N",
      "is_match": "Y",
      "itemgroup_seq": 7069,
      "repeating": "N"
    },
    {
      "study_oid": "C240001",
      "form_seq": 4078,
      "item_seq": 23696,
      "item_uid": "0808ab537aec4f07ab8a9907df0f3f9e",
      "item_oid": "ID_0146",
      "item_name": "MHENRTPT",
      "data_type": "Integer",
      "item_label": "중대이상반응(Serious Adverse Event) 병력 종료 여부",
      "input_type": "CheckBox",
      "input_type_label": "CheckBox",
      "code_list": "1=On-going",
      "ins_dt": "2025-03-12 15:21:30",
      "ins_id": "TEST0331",
      "ins_ip": "172.18.0.10",
      "upd_dt": "2025-03-12 15:21:30",
      "upd_id": "TEST0331",
      "upd_ip": "172.18.0.10",
      "mandatory": "N",
      "order_number": 10,
      "list_yn": "N",
      "is_match": "Y",
      "itemgroup_seq": 7070,
      "repeating": "N"
    },
    {
      "study_oid": "C240001",
      "form_seq": 4078,
      "item_seq": 23697,
      "item_uid": "4739b672418149a5add4237cbf9dd392",
      "item_oid": "ID_0147",
      "item_name": "ALKPHOS",
      "data_type": "Float",
      "item_label": "ALP 값",
      "item_length": "4",
      "significant_digits": "2",
      "input_type": "TextBox",
      "input_type_label": "TextBox",
      "ins_dt": "2025-03-12 15:21:48",
      "ins_id": "TEST0331",
      "ins_ip": "172.18.0.10",
      "upd_dt": "2025-03-12 15:21:48",
      "upd_id": "TEST0331",
      "upd_ip": "172.18.0.10",
      "length": "4.2",
      "mandatory": "N",
      "order_number": 11,
      "list_yn": "N",
      "is_match": "Y",
      "itemgroup_seq": 7070,
      "repeating": "N"
    },
    {
      "study_oid": "C240001",
      "form_seq": 4078,
      "item_seq": 23698,
      "item_uid": "506d7b36385c45a3bfd80035ccd9d4b4",
      "item_oid": "ID_0148",
      "item_name": "LBORRESU",
      "data_type": "Integer",
      "item_label": "Eosinophils 단위",
      "input_type": "DropDown",
      "input_type_label": "DropDown",
      "code_list": "1=%",
      "ins_dt": "2025-03-12 15:48:41",
      "ins_id": "TEST0331",
      "ins_ip": "172.18.0.10",
      "upd_dt": "2025-03-12 15:48:41",
      "upd_id": "TEST0331",
      "upd_ip": "172.18.0.10",
      "mandatory": "N",
      "order_number": 12,
      "list_yn": "N",
      "is_match": "Y",
      "itemgroup_seq": 7070,
      "repeating": "N"
    },
    {
      "study_oid": "C240001",
      "form_seq": 4078,
      "item_seq": 23699,
      "item_uid": "86ea17f703a24fdd949b7137058ac126",
      "item_oid": "ID_0149",
      "item_name": "LBORRESU_1",
      "data_type": "Integer",
      "item_label": "Gamma-GTP 단위",
      "input_type": "DropDown",
      "input_type_label": "DropDown",
      "code_list": "1=IU/L",
      "ins_dt": "2025-03-12 15:48:48",
      "ins_id": "TEST0331",
      "ins_ip": "172.18.0.10",
      "upd_dt": "2025-03-12 15:48:48",
      "upd_id": "TEST0331",
      "upd_ip": "172.18.0.10",
      "mandatory": "N",
      "order_number": 13,
      "list_yn": "N",
      "is_match": "Y",
      "itemgroup_seq": 7070,
      "repeating": "N"
    },
    {
      "study_oid": "C240001",
      "form_seq": 4078,
      "item_seq": 23700,
      "item_uid": "17e2ec25cfb242c991d0e598d3906497",
      "item_oid": "ID_0150",
      "item_name": "ITEM_394_2",
      "data_type": "String",
      "item_label": "RESEARCh 등록번호",
      "input_type": "TextBox",
      "input_type_label": "TextBox",
      "ins_dt": "2025-03-13 15:16:19",
      "ins_id": "TEST0331",
      "ins_ip": "172.18.0.10",
      "upd_dt": "2025-03-13 15:16:19",
      "upd_id": "TEST0331",
      "upd_ip": "172.18.0.10",
      "mandatory": "N",
      "order_number": 14,
      "list_yn": "N",
      "is_match": "Y",
      "itemgroup_seq": 7070,
      "repeating": "N"
    },
    {
      "study_oid": "C240001",
      "form_seq": 4078,
      "item_seq": 23701,
      "item_uid": "76fb01e888e54b6cbc15b89fb5c7edea",
      "item_oid": "ID_0151",
      "item_name": "SEX_1",
      "data_type": "String",
      "item_label": "Sex",
      "input_type": "TextBox",
      "input_type_label": "TextBox",
      "ins_dt": "2025-03-13 15:16:19",
      "ins_id": "TEST0331",
      "ins_ip": "172.18.0.10",
      "upd_dt": "2025-03-13 15:16:19",
      "upd_id": "TEST0331",
      "upd_ip": "172.18.0.10",
      "mandatory": "N",
      "order_number": 15,
      "list_yn": "N",
      "is_match": "Y",
      "itemgroup_seq": 7070,
      "repeating": "N"
    }
  ],
  "DVS": {
    "totResultMap": {},
    "evtResultList": [],
    "cfcResultList": []
  },
  "usernm": "t1",
  "CRF_AUTO_CALC_ORDER": [],
  "_MENU_AUTH_LVL": 2,
  "userorgannm": "알앤디 모티브",
  "CRF_RESERVED_WORDS": {
    "today": "2025-03-17",
    "icfdt": "2025-01-24",
    "age": 0,
    "ageunit": "일",
    "gender": "1",
    "birthdate": "2025-01-24",
    "visitnm": "Week 1.5",
    "calfrdt": "2025-01-24"
  },
  "ITEM_LIST": [
    {
      "study_oid": "C240001",
      "form_seq": 4078,
      "form_version_seq": 4542,
      "itemgroup_seq": 7064,
      "itemgroup_uid": "5cc5afed68af498dab36fcc2f5490537",
      "itemgroup_oid": "IG_036",
      "itemgroup_name": "1번 그룹입니다",
      "itemgroup_type": "T",
      "repeating": "N",
      "item_seq": 23687,
      "item_uid": "5bebf176cbc34b6c9c46408454d278ed",
      "item_oid": "ID_0137",
      "item_name": "ITEM_140_2",
      "item_name_label": "CRCRA 등록번호",
      "data_type": "String",
      "input_type": "TextBox",
      "item_length": "9",
      "form_data_seq": 0,
      "clinical_data_seq": 0,
      "itemgroup_repeatkey": 0,
      "orgn_item_value": "{No Data}",
      "orgn_item_label": "{No Data}",
      "item_value": "{No Data}",
      "item_label": "{No Data}"
    },
    {
      "study_oid": "C240001",
      "form_seq": 4078,
      "form_version_seq": 4542,
      "itemgroup_seq": 7064,
      "itemgroup_uid": "5cc5afed68af498dab36fcc2f5490537",
      "itemgroup_oid": "IG_036",
      "itemgroup_name": "1번 그룹입니다",
      "itemgroup_type": "T",
      "repeating": "N",
      "item_seq": 23688,
      "item_uid": "5e4cc23080d9465c825186a1d18c6717",
      "item_oid": "ID_0138",
      "item_name": "DMDTC_2",
      "item_name_label": "CRCRA 등록일",
      "data_type": "Date",
      "input_type": "Date",
      "form_data_seq": 0,
      "clinical_data_seq": 0,
      "itemgroup_repeatkey": 0,
      "orgn_item_value": "{No Data}",
      "orgn_item_label": "{No Data}",
      "item_value": "{No Data}",
      "item_label": "{No Data}"
    },
    {
      "study_oid": "C240001",
      "form_seq": 4078,
      "form_version_seq": 4542,
      "itemgroup_seq": 7068,
      "itemgroup_uid": "a3c4facc49244593825f6a6ab689dc36",
      "itemgroup_oid": "IG_037",
      "itemgroup_name": "2번 그룹입니다(얘는 설명없음)",
      "itemgroup_type": "T",
      "repeating": "N",
      "item_seq": 23689,
      "item_uid": "4dfdd36777604e4e8f10d14d453add45",
      "item_oid": "ID_0139",
      "item_name": "Calculate_1",
      "item_name_label": "Calculate",
      "data_type": "Integer",
      "input_type": "Calculate",
      "item_length": "5",
      "form_data_seq": 0,
      "clinical_data_seq": 0,
      "itemgroup_repeatkey": 0,
      "orgn_item_value": "{No Data}",
      "orgn_item_label": "{No Data}",
      "item_value": "{No Data}",
      "item_label": "{No Data}"
    },
    {
      "study_oid": "C240001",
      "form_seq": 4078,
      "form_version_seq": 4542,
      "itemgroup_seq": 7068,
      "itemgroup_uid": "a3c4facc49244593825f6a6ab689dc36",
      "itemgroup_oid": "IG_037",
      "itemgroup_name": "2번 그룹입니다(얘는 설명없음)",
      "itemgroup_type": "T",
      "repeating": "N",
      "item_seq": 23690,
      "item_uid": "2ce1096de4114254ba2fb6b1ee1671b1",
      "item_oid": "ID_0140",
      "item_name": "COVAL_1",
      "item_name_label": "biomarker 혈액 검체 미채취 기타 이유",
      "data_type": "String",
      "input_type": "Comments",
      "form_data_seq": 0,
      "clinical_data_seq": 0,
      "itemgroup_repeatkey": 0,
      "orgn_item_value": "{No Data}",
      "orgn_item_label": "{No Data}",
      "item_value": "{No Data}",
      "item_label": "{No Data}"
    },
    {
      "study_oid": "C240001",
      "form_seq": 4078,
      "form_version_seq": 4542,
      "itemgroup_seq": 7068,
      "itemgroup_uid": "a3c4facc49244593825f6a6ab689dc36",
      "itemgroup_oid": "IG_037",
      "itemgroup_name": "2번 그룹입니다(얘는 설명없음)",
      "itemgroup_type": "T",
      "repeating": "N",
      "item_seq": 23691,
      "item_uid": "c60d7d72b69a497d93bca1476b836877",
      "item_oid": "ID_0141",
      "item_name": "AGE_5",
      "item_name_label": "AGE",
      "data_type": "Integer",
      "input_type": "TextBox",
      "item_length": "3",
      "form_data_seq": 0,
      "clinical_data_seq": 0,
      "itemgroup_repeatkey": 0,
      "orgn_item_value": "{No Data}",
      "orgn_item_label": "{No Data}",
      "item_value": "{No Data}",
      "item_label": "{No Data}"
    },
    {
      "study_oid": "C240001",
      "form_seq": 4078,
      "form_version_seq": 4542,
      "itemgroup_seq": 7069,
      "itemgroup_uid": "6214dfe08226463e8efa327674051ff1",
      "itemgroup_oid": "IG_038",
      "itemgroup_name": "3번 그룹",
      "itemgroup_type": "T",
      "repeating": "N",
      "item_seq": 23692,
      "item_uid": "8606ceda52ce45e7a339f406884418eb",
      "item_oid": "ID_0142",
      "item_name": "VISIT",
      "item_name_label": "예정된 방문 여부",
      "data_type": "Integer",
      "input_type": "Radio",
      "code_list": "1=Planned|2=Unscheduled",
      "form_data_seq": 0,
      "clinical_data_seq": 0,
      "itemgroup_repeatkey": 0,
      "orgn_item_value": "{No Data}",
      "orgn_item_label": "{No Data}",
      "item_value": "{No Data}",
      "item_label": "{No Data}"
    },
    {
      "study_oid": "C240001",
      "form_seq": 4078,
      "form_version_seq": 4542,
      "itemgroup_seq": 7069,
      "itemgroup_uid": "6214dfe08226463e8efa327674051ff1",
      "itemgroup_oid": "IG_038",
      "itemgroup_name": "3번 그룹",
      "itemgroup_type": "T",
      "repeating": "N",
      "item_seq": 23693,
      "item_uid": "101a46966a3444389b025cdcc708e136",
      "item_oid": "ID_0143",
      "item_name": "EXDOSU_1",
      "item_name_label": "약물 투여 단위 종류",
      "data_type": "Integer",
      "input_type": "DropDown",
      "code_list": "1=mg|2=복합제(tab/cap)",
      "form_data_seq": 0,
      "clinical_data_seq": 0,
      "itemgroup_repeatkey": 0,
      "orgn_item_value": "{No Data}",
      "orgn_item_label": "{No Data}",
      "item_value": "{No Data}",
      "item_label": "{No Data}"
    },
    {
      "study_oid": "C240001",
      "form_seq": 4078,
      "form_version_seq": 4542,
      "itemgroup_seq": 7069,
      "itemgroup_uid": "6214dfe08226463e8efa327674051ff1",
      "itemgroup_oid": "IG_038",
      "itemgroup_name": "3번 그룹",
      "itemgroup_type": "T",
      "repeating": "N",
      "item_seq": 23694,
      "item_uid": "57089ae0e4e1469695f7ed9694cbadf9",
      "item_oid": "ID_0144",
      "item_name": "SUDOSTOT",
      "item_name_label": "흡연량",
      "data_type": "String",
      "input_type": "TextBox",
      "form_data_seq": 0,
      "clinical_data_seq": 0,
      "itemgroup_repeatkey": 0,
      "orgn_item_value": "{No Data}",
      "orgn_item_label": "{No Data}",
      "item_value": "{No Data}",
      "item_label": "{No Data}"
    },
    {
      "study_oid": "C240001",
      "form_seq": 4078,
      "form_version_seq": 4542,
      "itemgroup_seq": 7069,
      "itemgroup_uid": "6214dfe08226463e8efa327674051ff1",
      "itemgroup_oid": "IG_038",
      "itemgroup_name": "3번 그룹",
      "itemgroup_type": "T",
      "repeating": "N",
      "item_seq": 23695,
      "item_uid": "ce3c661a01574127a41f6f44c9c72d6b",
      "item_oid": "ID_0145",
      "item_name": "MHSTDTC",
      "item_name_label": "Date of Surgery",
      "data_type": "String",
      "input_type": "TextBox",
      "item_length": "6",
      "form_data_seq": 0,
      "clinical_data_seq": 0,
      "itemgroup_repeatkey": 0,
      "orgn_item_value": "{No Data}",
      "orgn_item_label": "{No Data}",
      "item_value": "{No Data}",
      "item_label": "{No Data}"
    },
    {
      "study_oid": "C240001",
      "form_seq": 4078,
      "form_version_seq": 4542,
      "itemgroup_seq": 7070,
      "itemgroup_uid": "d793be0611d44a678f9e615b4bf7dac2",
      "itemgroup_oid": "IG_039",
      "itemgroup_type": "T",
      "repeating": "N",
      "item_seq": 23696,
      "item_uid": "0808ab537aec4f07ab8a9907df0f3f9e",
      "item_oid": "ID_0146",
      "item_name": "MHENRTPT",
      "item_name_label": "중대이상반응(Serious Adverse Event) 병력 종료 여부",
      "data_type": "Integer",
      "input_type": "CheckBox",
      "code_list": "1=On-going",
      "form_data_seq": 0,
      "clinical_data_seq": 0,
      "itemgroup_repeatkey": 0,
      "orgn_item_value": "{No Data}",
      "orgn_item_label": "{No Data}",
      "item_value": "{No Data}",
      "item_label": "{No Data}"
    },
    {
      "study_oid": "C240001",
      "form_seq": 4078,
      "form_version_seq": 4542,
      "itemgroup_seq": 7070,
      "itemgroup_uid": "d793be0611d44a678f9e615b4bf7dac2",
      "itemgroup_oid": "IG_039",
      "itemgroup_type": "T",
      "repeating": "N",
      "item_seq": 23697,
      "item_uid": "4739b672418149a5add4237cbf9dd392",
      "item_oid": "ID_0147",
      "item_name": "ALKPHOS",
      "item_name_label": "ALP 값",
      "data_type": "Float",
      "input_type": "TextBox",
      "item_length": "4",
      "form_data_seq": 0,
      "clinical_data_seq": 0,
      "itemgroup_repeatkey": 0,
      "orgn_item_value": "{No Data}",
      "orgn_item_label": "{No Data}",
      "item_value": "{No Data}",
      "item_label": "{No Data}"
    },
    {
      "study_oid": "C240001",
      "form_seq": 4078,
      "form_version_seq": 4542,
      "itemgroup_seq": 7070,
      "itemgroup_uid": "d793be0611d44a678f9e615b4bf7dac2",
      "itemgroup_oid": "IG_039",
      "itemgroup_type": "T",
      "repeating": "N",
      "item_seq": 23698,
      "item_uid": "506d7b36385c45a3bfd80035ccd9d4b4",
      "item_oid": "ID_0148",
      "item_name": "LBORRESU",
      "item_name_label": "Eosinophils 단위",
      "data_type": "Integer",
      "input_type": "DropDown",
      "code_list": "1=%",
      "form_data_seq": 0,
      "clinical_data_seq": 0,
      "itemgroup_repeatkey": 0,
      "orgn_item_value": "{No Data}",
      "orgn_item_label": "{No Data}",
      "item_value": "{No Data}",
      "item_label": "{No Data}"
    },
    {
      "study_oid": "C240001",
      "form_seq": 4078,
      "form_version_seq": 4542,
      "itemgroup_seq": 7070,
      "itemgroup_uid": "d793be0611d44a678f9e615b4bf7dac2",
      "itemgroup_oid": "IG_039",
      "itemgroup_type": "T",
      "repeating": "N",
      "item_seq": 23699,
      "item_uid": "86ea17f703a24fdd949b7137058ac126",
      "item_oid": "ID_0149",
      "item_name": "LBORRESU_1",
      "item_name_label": "Gamma-GTP 단위",
      "data_type": "Integer",
      "input_type": "DropDown",
      "code_list": "1=IU/L",
      "form_data_seq": 0,
      "clinical_data_seq": 0,
      "itemgroup_repeatkey": 0,
      "orgn_item_value": "{No Data}",
      "orgn_item_label": "{No Data}",
      "item_value": "{No Data}",
      "item_label": "{No Data}"
    },
    {
      "study_oid": "C240001",
      "form_seq": 4078,
      "form_version_seq": 4542,
      "itemgroup_seq": 7070,
      "itemgroup_uid": "d793be0611d44a678f9e615b4bf7dac2",
      "itemgroup_oid": "IG_039",
      "itemgroup_type": "T",
      "repeating": "N",
      "item_seq": 23700,
      "item_uid": "17e2ec25cfb242c991d0e598d3906497",
      "item_oid": "ID_0150",
      "item_name": "ITEM_394_2",
      "item_name_label": "RESEARCh 등록번호",
      "data_type": "String",
      "input_type": "TextBox",
      "form_data_seq": 0,
      "clinical_data_seq": 0,
      "itemgroup_repeatkey": 0,
      "orgn_item_value": "{No Data}",
      "orgn_item_label": "{No Data}",
      "item_value": "{No Data}",
      "item_label": "{No Data}"
    },
    {
      "study_oid": "C240001",
      "form_seq": 4078,
      "form_version_seq": 4542,
      "itemgroup_seq": 7070,
      "itemgroup_uid": "d793be0611d44a678f9e615b4bf7dac2",
      "itemgroup_oid": "IG_039",
      "itemgroup_type": "T",
      "repeating": "N",
      "item_seq": 23701,
      "item_uid": "76fb01e888e54b6cbc15b89fb5c7edea",
      "item_oid": "ID_0151",
      "item_name": "SEX_1",
      "item_name_label": "Sex",
      "data_type": "String",
      "input_type": "TextBox",
      "form_data_seq": 0,
      "clinical_data_seq": 0,
      "itemgroup_repeatkey": 0,
      "orgn_item_value": "{No Data}",
      "orgn_item_label": "{No Data}",
      "item_value": "{No Data}",
      "item_label": "{No Data}"
    }
  ],
  "_RSLT_MSG": "정상적으로 조회되었습니다.",
  "userid": "TEST0331"
}
''';

  static String srchPathSchList = '''
{
  "usernm": "t1",
  "_USERTYPE": "2",
  "_MENU_AUTH_LVL": 2,
  "_USERID": "TEST0331",
  "userorgannm": "알앤디 모티브",
  "_RSLT_MSG": "정상적으로 조회되었습니다.",
  "userid": "TEST0331",
  "visitList": [
    {
      "STUDYEVENT_SEQ": 2521,
      "STUDYEVENT_NAME": "Baseline",
      "EVENT_STATUS": "A",
      "IS_NEW": "N",
      "STUDYEVENT_REPEATKEY": 1,
      "VISIT_SEQ": 1,
      "FORM_SEQ": 3781,
      "FORM_NAME": "정보 수집일",
      "NO_FORM": 3781,
      "FV_STATUS": "O",
      "FORM_REPEATING": "N",
      "FORM_REPEATKEY": 1,
      "FE_SEQ": 1,
      "VISIT_ORDER": 1,
      "EVENT_CYCLE": "d",
      "EVENT_INTERVAL": "7",
      "EVENT_TYPE": "Scheduled",
      "PREV_STUDYEVENT_OID": 0,
      "SCHEDULE_YN": "Y",
      "PLANNED_DATE": "2025-01-31",
      "MIN_PLANNED_DATE": "1997-09-16",
      "MAX_PLANNED_DATE": "2052-06-17",
      "VISIT_DATE": "2025-01-24",
      "PAST_YN": "N",
      "VISIT_YN": "Y",
      "FORM_STATUS": "R",
      "CRF_DATE": "2025-01-24",
      "NR_YN": "N",
      "FORM_DATA_SEQ": 0,
      "STUDYEVENT_DATA_SEQ": 115720,
      "MANDATORY": "Y",
      "FORM_CNT": 1,
      "QRY_NEW": 0,
      "QRY_RS": 0,
      "QRY_CLS": 0,
      "DRUGNO": "-",
      "DRUGRESN": "-"
    },
    {
      "STUDYEVENT_SEQ": 2521,
      "STUDYEVENT_NAME": "Baseline",
      "EVENT_STATUS": "A",
      "IS_NEW": "N",
      "STUDYEVENT_REPEATKEY": 1,
      "VISIT_SEQ": 1,
      "FORM_SEQ": 3778,
      "FORM_NAME": "기저 임상 정보",
      "NO_FORM": 3778,
      "FV_STATUS": "A",
      "FORM_REPEATING": "N",
      "FORM_REPEATKEY": 1,
      "FE_SEQ": 1,
      "VISIT_ORDER": 1,
      "EVENT_CYCLE": "d",
      "EVENT_INTERVAL": "7",
      "EVENT_TYPE": "Scheduled",
      "PREV_STUDYEVENT_OID": 0,
      "SCHEDULE_YN": "Y",
      "PLANNED_DATE": "2025-01-31",
      "MIN_PLANNED_DATE": "1997-09-16",
      "MAX_PLANNED_DATE": "2052-06-17",
      "VISIT_DATE": "2025-01-24",
      "PAST_YN": "N",
      "VISIT_YN": "Y",
      "FORM_STATUS": "Y",
      "CRF_DATE": "2025-01-24",
      "NR_YN": "N",
      "SDV_STATUS": "N",
      "LOCK_STATUS": "N",
      "FORM_DATA_SEQ": 90207,
      "STUDYEVENT_DATA_SEQ": 115720,
      "MANDATORY": "Y",
      "FORM_CNT": 1,
      "QRY_NEW": 1,
      "QRY_RS": 0,
      "QRY_CLS": 0,
      "DRUGNO": "-",
      "DRUGRESN": "-"
    },
    {
      "STUDYEVENT_SEQ": 2521,
      "STUDYEVENT_NAME": "Baseline",
      "EVENT_STATUS": "A",
      "IS_NEW": "N",
      "STUDYEVENT_REPEATKEY": 1,
      "VISIT_SEQ": 1,
      "FORM_SEQ": 3779,
      "FORM_NAME": "병용약물",
      "NO_FORM": 3779,
      "FV_STATUS": "A",
      "FORM_REPEATING": "N",
      "FORM_REPEATKEY": 1,
      "FE_SEQ": 1,
      "VISIT_ORDER": 1,
      "EVENT_CYCLE": "d",
      "EVENT_INTERVAL": "7",
      "EVENT_TYPE": "Scheduled",
      "PREV_STUDYEVENT_OID": 0,
      "SCHEDULE_YN": "Y",
      "PLANNED_DATE": "2025-01-31",
      "MIN_PLANNED_DATE": "1997-09-16",
      "MAX_PLANNED_DATE": "2052-06-17",
      "VISIT_DATE": "2025-01-24",
      "PAST_YN": "N",
      "VISIT_YN": "Y",
      "FORM_STATUS": "R",
      "CRF_DATE": "2025-01-24",
      "NR_YN": "N",
      "FORM_DATA_SEQ": 0,
      "STUDYEVENT_DATA_SEQ": 115720,
      "MANDATORY": "Y",
      "FORM_CNT": 1,
      "QRY_NEW": 0,
      "QRY_RS": 0,
      "QRY_CLS": 0,
      "DRUGNO": "-",
      "DRUGRESN": "-"
    },
    {
      "STUDYEVENT_SEQ": 2581,
      "STUDYEVENT_NAME": "Week 1",
      "EVENT_STATUS": "A",
      "IS_NEW": "N",
      "STUDYEVENT_REPEATKEY": 1,
      "VISIT_SEQ": 1,
      "FORM_SEQ": 3836,
      "FORM_NAME": "ePRO용 설문지",
      "NO_FORM": 3836,
      "FV_STATUS": "A",
      "FORM_REPEATING": "N",
      "FORM_REPEATKEY": 1,
      "FE_SEQ": 1,
      "VISIT_ORDER": 2,
      "EVENT_CYCLE": "d",
      "EVENT_INTERVAL": "15",
      "EVENT_TYPE": "Scheduled",
      "PREV_STUDYEVENT_OID": 2521,
      "SCHEDULE_YN": "Y",
      "PLANNED_DATE": "2025-02-15",
      "MIN_PLANNED_DATE": "1997-10-01",
      "MAX_PLANNED_DATE": "2052-07-02",
      "VISIT_DATE": "2025-01-24",
      "PAST_YN": "N",
      "VISIT_YN": "Y",
      "FORM_STATUS": "Y",
      "CRF_DATE": "2025-01-24",
      "NR_YN": "N",
      "SDV_STATUS": "N",
      "LOCK_STATUS": "N",
      "FORM_DATA_SEQ": 90264,
      "STUDYEVENT_DATA_SEQ": 115721,
      "MANDATORY": "Y",
      "FORM_CNT": 1,
      "QRY_NEW": 0,
      "QRY_RS": 0,
      "QRY_CLS": 0,
      "DRUGNO": "-",
      "DRUGRESN": "-"
    },
    {
      "STUDYEVENT_SEQ": 2581,
      "STUDYEVENT_NAME": "Week 1",
      "EVENT_STATUS": "A",
      "IS_NEW": "N",
      "STUDYEVENT_REPEATKEY": 1,
      "VISIT_SEQ": 1,
      "FORM_SEQ": 3877,
      "FORM_NAME": "ePRO용 천식 설문지",
      "NO_FORM": 3877,
      "FV_STATUS": "A",
      "FORM_REPEATING": "Y",
      "FORM_REPEATKEY": 2,
      "FE_SEQ": 1,
      "VISIT_ORDER": 2,
      "EVENT_CYCLE": "d",
      "EVENT_INTERVAL": "15",
      "EVENT_TYPE": "Scheduled",
      "PREV_STUDYEVENT_OID": 2521,
      "SCHEDULE_YN": "Y",
      "PLANNED_DATE": "2025-02-15",
      "MIN_PLANNED_DATE": "1997-10-01",
      "MAX_PLANNED_DATE": "2052-07-02",
      "VISIT_DATE": "2025-01-24",
      "PAST_YN": "N",
      "VISIT_YN": "Y",
      "FORM_STATUS": "R",
      "CRF_DATE": "2025-01-24",
      "NR_YN": "N",
      "FORM_DATA_SEQ": 0,
      "STUDYEVENT_DATA_SEQ": 115721,
      "MANDATORY": "Y",
      "FORM_CNT": 1,
      "QRY_NEW": 0,
      "QRY_RS": 0,
      "QRY_CLS": 0,
      "DRUGNO": "-",
      "DRUGRESN": "-"
    },
    {
      "STUDYEVENT_SEQ": 2581,
      "STUDYEVENT_NAME": "Week 1",
      "EVENT_STATUS": "A",
      "IS_NEW": "N",
      "STUDYEVENT_REPEATKEY": 1,
      "VISIT_SEQ": 1,
      "FORM_SEQ": 3878,
      "FORM_NAME": "ePRO용 영양설문",
      "NO_FORM": 3878,
      "FV_STATUS": "O",
      "FORM_REPEATING": "N",
      "FORM_REPEATKEY": 1,
      "FE_SEQ": 1,
      "VISIT_ORDER": 2,
      "EVENT_CYCLE": "d",
      "EVENT_INTERVAL": "15",
      "EVENT_TYPE": "Scheduled",
      "PREV_STUDYEVENT_OID": 2521,
      "SCHEDULE_YN": "Y",
      "PLANNED_DATE": "2025-02-15",
      "MIN_PLANNED_DATE": "1997-10-01",
      "MAX_PLANNED_DATE": "2052-07-02",
      "VISIT_DATE": "2025-01-24",
      "PAST_YN": "N",
      "VISIT_YN": "Y",
      "FORM_STATUS": "R",
      "CRF_DATE": "2025-01-24",
      "NR_YN": "N",
      "FORM_DATA_SEQ": 0,
      "STUDYEVENT_DATA_SEQ": 115721,
      "MANDATORY": "Y",
      "FORM_CNT": 1,
      "QRY_NEW": 0,
      "QRY_RS": 0,
      "QRY_CLS": 0,
      "DRUGNO": "-",
      "DRUGRESN": "-"
    },
    {
      "STUDYEVENT_SEQ": 2582,
      "STUDYEVENT_NAME": "Week 2 (방문)",
      "EVENT_STATUS": "A",
      "IS_NEW": "N",
      "STUDYEVENT_REPEATKEY": 1,
      "VISIT_SEQ": 1,
      "FORM_SEQ": 3780,
      "FORM_NAME": "시험약",
      "NO_FORM": 3780,
      "FV_STATUS": "A",
      "FORM_REPEATING": "N",
      "FORM_REPEATKEY": 1,
      "FE_SEQ": 1,
      "VISIT_ORDER": 3,
      "EVENT_CYCLE": "d",
      "EVENT_INTERVAL": "30",
      "EVENT_TYPE": "Scheduled",
      "PREV_STUDYEVENT_OID": 2521,
      "SCHEDULE_YN": "Y",
      "PLANNED_DATE": "2025-02-23",
      "MIN_PLANNED_DATE": "1997-10-09",
      "MAX_PLANNED_DATE": "2052-07-10",
      "VISIT_DATE": "2025-03-18",
      "PAST_YN": "N",
      "VISIT_YN": "Y",
      "FORM_STATUS": "R",
      "CRF_DATE": "2025-03-18",
      "NR_YN": "N",
      "FORM_DATA_SEQ": 0,
      "STUDYEVENT_DATA_SEQ": 115722,
      "MANDATORY": "Y",
      "FORM_CNT": 0,
      "QRY_NEW": 0,
      "QRY_RS": 0,
      "QRY_CLS": 0,
      "DRUGNO": "-",
      "DRUGRESN": "-"
    },
    {
      "STUDYEVENT_SEQ": 2582,
      "STUDYEVENT_NAME": "Week 2 (방문)",
      "EVENT_STATUS": "A",
      "IS_NEW": "N",
      "STUDYEVENT_REPEATKEY": 1,
      "VISIT_SEQ": 1,
      "FORM_SEQ": 3879,
      "FORM_NAME": "혈액검사",
      "NO_FORM": 3879,
      "FV_STATUS": "A",
      "FORM_REPEATING": "N",
      "FORM_REPEATKEY": 1,
      "FE_SEQ": 1,
      "VISIT_ORDER": 3,
      "EVENT_CYCLE": "d",
      "EVENT_INTERVAL": "30",
      "EVENT_TYPE": "Scheduled",
      "PREV_STUDYEVENT_OID": 2521,
      "SCHEDULE_YN": "Y",
      "PLANNED_DATE": "2025-02-23",
      "MIN_PLANNED_DATE": "1997-10-09",
      "MAX_PLANNED_DATE": "2052-07-10",
      "VISIT_DATE": "2025-03-18",
      "PAST_YN": "N",
      "VISIT_YN": "Y",
      "FORM_STATUS": "R",
      "CRF_DATE": "2025-03-18",
      "NR_YN": "N",
      "FORM_DATA_SEQ": 0,
      "STUDYEVENT_DATA_SEQ": 115722,
      "MANDATORY": "Y",
      "FORM_CNT": 0,
      "QRY_NEW": 0,
      "QRY_RS": 0,
      "QRY_CLS": 0,
      "DRUGNO": "-",
      "DRUGRESN": "-"
    },
    {
      "STUDYEVENT_SEQ": 2583,
      "STUDYEVENT_NAME": "Week 3",
      "EVENT_STATUS": "A",
      "IS_NEW": "N",
      "STUDYEVENT_REPEATKEY": 1,
      "VISIT_SEQ": 1,
      "FORM_SEQ": 3836,
      "FORM_NAME": "ePRO용 설문지",
      "NO_FORM": 3836,
      "FV_STATUS": "A",
      "FORM_REPEATING": "N",
      "FORM_REPEATKEY": 1,
      "FE_SEQ": 1,
      "VISIT_ORDER": 4,
      "EVENT_CYCLE": "d",
      "EVENT_INTERVAL": "45",
      "EVENT_TYPE": "Scheduled",
      "PREV_STUDYEVENT_OID": 2521,
      "SCHEDULE_YN": "Y",
      "PLANNED_DATE": "2025-03-10",
      "MIN_PLANNED_DATE": "1997-10-24",
      "MAX_PLANNED_DATE": "2052-07-25",
      "VISIT_DATE": "2025-03-17",
      "PAST_YN": "N",
      "VISIT_YN": "Y",
      "FORM_STATUS": "R",
      "CRF_DATE": "2025-03-17",
      "NR_YN": "N",
      "FORM_DATA_SEQ": 0,
      "STUDYEVENT_DATA_SEQ": 115723,
      "MANDATORY": "Y",
      "FORM_CNT": 0,
      "QRY_NEW": 0,
      "QRY_RS": 0,
      "QRY_CLS": 0,
      "DRUGNO": "-",
      "DRUGRESN": "-"
    },
    {
      "STUDYEVENT_SEQ": 2583,
      "STUDYEVENT_NAME": "Week 3",
      "EVENT_STATUS": "A",
      "IS_NEW": "N",
      "STUDYEVENT_REPEATKEY": 1,
      "VISIT_SEQ": 1,
      "FORM_SEQ": 3877,
      "FORM_NAME": "ePRO용 천식 설문지",
      "NO_FORM": 3877,
      "FV_STATUS": "A",
      "FORM_REPEATING": "Y",
      "FORM_REPEATKEY": 1,
      "FE_SEQ": 1,
      "VISIT_ORDER": 4,
      "EVENT_CYCLE": "d",
      "EVENT_INTERVAL": "45",
      "EVENT_TYPE": "Scheduled",
      "PREV_STUDYEVENT_OID": 2521,
      "SCHEDULE_YN": "Y",
      "PLANNED_DATE": "2025-03-10",
      "MIN_PLANNED_DATE": "1997-10-24",
      "MAX_PLANNED_DATE": "2052-07-25",
      "VISIT_DATE": "2025-03-17",
      "PAST_YN": "N",
      "VISIT_YN": "Y",
      "FORM_STATUS": "R",
      "CRF_DATE": "2025-03-17",
      "NR_YN": "N",
      "FORM_DATA_SEQ": 0,
      "STUDYEVENT_DATA_SEQ": 115723,
      "MANDATORY": "Y",
      "FORM_CNT": 0,
      "QRY_NEW": 0,
      "QRY_RS": 0,
      "QRY_CLS": 0,
      "DRUGNO": "-",
      "DRUGRESN": "-"
    },
    {
      "STUDYEVENT_SEQ": 2583,
      "STUDYEVENT_NAME": "Week 3",
      "EVENT_STATUS": "A",
      "IS_NEW": "N",
      "STUDYEVENT_REPEATKEY": 1,
      "VISIT_SEQ": 1,
      "FORM_SEQ": 3878,
      "FORM_NAME": "ePRO용 영양설문",
      "NO_FORM": 3878,
      "FV_STATUS": "O",
      "FORM_REPEATING": "N",
      "FORM_REPEATKEY": 1,
      "FE_SEQ": 1,
      "VISIT_ORDER": 4,
      "EVENT_CYCLE": "d",
      "EVENT_INTERVAL": "45",
      "EVENT_TYPE": "Scheduled",
      "PREV_STUDYEVENT_OID": 2521,
      "SCHEDULE_YN": "Y",
      "PLANNED_DATE": "2025-03-10",
      "MIN_PLANNED_DATE": "1997-10-24",
      "MAX_PLANNED_DATE": "2052-07-25",
      "VISIT_DATE": "2025-03-17",
      "PAST_YN": "N",
      "VISIT_YN": "Y",
      "FORM_STATUS": "R",
      "CRF_DATE": "2025-03-17",
      "NR_YN": "N",
      "FORM_DATA_SEQ": 0,
      "STUDYEVENT_DATA_SEQ": 115723,
      "MANDATORY": "Y",
      "FORM_CNT": 0,
      "QRY_NEW": 0,
      "QRY_RS": 0,
      "QRY_CLS": 0,
      "DRUGNO": "-",
      "DRUGRESN": "-"
    },
    {
      "STUDYEVENT_SEQ": 2584,
      "STUDYEVENT_NAME": "End of Study",
      "EVENT_STATUS": "A",
      "IS_NEW": "N",
      "STUDYEVENT_REPEATKEY": 1,
      "VISIT_SEQ": 1,
      "FORM_SEQ": 3779,
      "FORM_NAME": "병용약물",
      "NO_FORM": 3779,
      "FV_STATUS": "A",
      "FORM_REPEATING": "N",
      "FORM_REPEATKEY": 1,
      "FE_SEQ": 1,
      "VISIT_ORDER": 5,
      "EVENT_CYCLE": "d",
      "EVENT_INTERVAL": "45",
      "EVENT_TYPE": "Scheduled",
      "PREV_STUDYEVENT_OID": 2521,
      "SCHEDULE_YN": "Y",
      "PLANNED_DATE": "2025-03-17",
      "MIN_PLANNED_DATE": "1997-10-31",
      "MAX_PLANNED_DATE": "2052-08-01",
      "VISIT_DATE": "2025-01-24",
      "PAST_YN": "N",
      "VISIT_YN": "Y",
      "FORM_STATUS": "R",
      "CRF_DATE": "2025-01-24",
      "NR_YN": "N",
      "FORM_DATA_SEQ": 0,
      "STUDYEVENT_DATA_SEQ": 115724,
      "MANDATORY": "Y",
      "FORM_CNT": 0,
      "QRY_NEW": 0,
      "QRY_RS": 0,
      "QRY_CLS": 0,
      "DRUGNO": "-",
      "DRUGRESN": "-"
    },
    {
      "STUDYEVENT_SEQ": 2584,
      "STUDYEVENT_NAME": "End of Study",
      "EVENT_STATUS": "A",
      "IS_NEW": "N",
      "STUDYEVENT_REPEATKEY": 1,
      "VISIT_SEQ": 1,
      "FORM_SEQ": 3780,
      "FORM_NAME": "시험약",
      "NO_FORM": 3780,
      "FV_STATUS": "A",
      "FORM_REPEATING": "N",
      "FORM_REPEATKEY": 1,
      "FE_SEQ": 1,
      "VISIT_ORDER": 5,
      "EVENT_CYCLE": "d",
      "EVENT_INTERVAL": "45",
      "EVENT_TYPE": "Scheduled",
      "PREV_STUDYEVENT_OID": 2521,
      "SCHEDULE_YN": "Y",
      "PLANNED_DATE": "2025-03-17",
      "MIN_PLANNED_DATE": "1997-10-31",
      "MAX_PLANNED_DATE": "2052-08-01",
      "VISIT_DATE": "2025-01-24",
      "PAST_YN": "N",
      "VISIT_YN": "Y",
      "FORM_STATUS": "R",
      "CRF_DATE": "2025-01-24",
      "NR_YN": "N",
      "FORM_DATA_SEQ": 0,
      "STUDYEVENT_DATA_SEQ": 115724,
      "MANDATORY": "Y",
      "FORM_CNT": 0,
      "QRY_NEW": 0,
      "QRY_RS": 0,
      "QRY_CLS": 0,
      "DRUGNO": "-",
      "DRUGRESN": "-"
    },
    {
      "STUDYEVENT_SEQ": 2742,
      "STUDYEVENT_NAME": "Week 1.5",
      "EVENT_STATUS": "A",
      "IS_NEW": "N",
      "STUDYEVENT_REPEATKEY": 1,
      "VISIT_SEQ": 1,
      "FORM_SEQ": 4078,
      "FORM_NAME": "All Types",
      "NO_FORM": 4078,
      "FV_STATUS": "A",
      "FORM_REPEATING": "N",
      "FORM_REPEATKEY": 1,
      "FE_SEQ": 1,
      "VISIT_ORDER": 9,
      "EVENT_CYCLE": "d",
      "EVENT_INTERVAL": "3",
      "EVENT_TYPE": "Scheduled",
      "PREV_STUDYEVENT_OID": 2581,
      "SCHEDULE_YN": "Y",
      "PLANNED_DATE": "2025-01-27",
      "MIN_PLANNED_DATE": "1997-09-12",
      "MAX_PLANNED_DATE": "2052-06-13",
      "PAST_YN": "Past Scheduled Date",
      "VISIT_YN": "N",
      "FORM_STATUS": "R",
      "NR_YN": "N",
      "FORM_DATA_SEQ": 0,
      "STUDYEVENT_DATA_SEQ": 115889,
      "MANDATORY": "Y",
      "FORM_CNT": 0,
      "QRY_NEW": 0,
      "QRY_RS": 0,
      "QRY_CLS": 0,
      "DRUGNO": "-",
      "DRUGRESN": "-"
    }
  ]
}
''';
}
